### ISSUE TITLE
This needs to be bigger.

### ISSUE THREAD

**Issue by bunchc** [mjbrender/12-days-of-commitmas#12]
Following on from a conversation on twitter. I strongly believe this needs to be HUGE. That is, the start is great, however, as a collective, we have so much in the way of applied skill and knowledge, and I think this project and others like it can help that flourish.

Some thoughts:
- Can we expand this into a 30-in30 format?
- Identify projects that are receptive to non-developer fixes.
- Identify an onramp for non-coders. Things like bash scrpits to tshoot, collect logs, deploy things, iptables, etc.

**Comment by mjbrender** [comment]
:+1: to the scoping. This format felt quite expandable last year, especially under the vBrownBag banner.

Q for you @bunchc - what's the 30-in-30 format specifically? The holiday season can be a way to get people started and then there's a continue on element.

**Comment by jfrappier** [comment]
I think do a thing a day for 30 days, similar to #vDM 30-in-30 blog posts. So we'd come up with 30 different tasks that people do each day?

**Comment by vCloudernBeer** [comment]
I am so excited about this.  I need this push for myself.

**Comment by jfrappier** [comment]
@bunchc if we have shows to support this, they might be short...that okay? Also likely need a break for Christmas day

**Comment by anthonyrhook** [comment]
>There value in helping people get Windows/Mac/Linux setup ... e.g. install tools, generate keys etc?

Absolutely - it's nice to have a guide for anyone's first time with this stuff.

**Comment by timmycarr** [comment]
Happy to help with Linux/MacOSX setups.

**Comment by jfrappier** [comment]
This is so much easier than email

**Comment by vCloudernBeer** [comment]
etherpad is also good for group discussion

**Comment by jfrappier** [comment]
Any good, SMALL, projects we could approach about helping with docs for non-coders? I worry Docker and OpenStack might shun non-devs because we aren't cool enough (just my experience).

**Comment by vCloudernBeer** [comment]
But both Docker and OpenStack also have the operation side that needs documentation.

**Comment by complexsplit** [comment]
There are sites like http://openhatch.org that might be able to assist with project finding/matching.

**Comment by anthonyrhook** [comment]
Documentation is always needed in the Ubuntu world, for what that's worth, too.

**Comment by anthonyrhook** [comment]
Also, one idea could be useful powershell snippets, perhaps fix a bug in vCheck (for vSphere), there's a ton of possibilities.

**Comment by jfrappier** [comment]
I like that for the vPeople @anthonyrhook - maybe for that challenge we post a few links to repos for people to look at?

**Comment by vCloudernBeer** [comment]
You think we can do some documentation on VMware's project Photon? It will be useful for our resume along the commit skill that we acquired during the process

**Comment by bunchc** [comment]
@jfrappier re: shows, yes. Short and to the point is fine. I think momentum will be key.
@mjbrender the 30-in-30 format, when applied to blogs was 30 posts in 30 days. I like the task idea proposed by @jfrappier. 

Because folks will be starting from different points / backgrounds, I also think having a number of projects to contribute to would be ideal. We can approach and maybe get a resource or two from some of the larger ones to help with onboarding, and provide a list & descriptions at each level. Say, Advanced would be interesting bug fixes, Middling could be low-hanging bugs, and beginner doc fixes?

**Comment by complexsplit** [comment]
https://www.facebook.com/notes/alok-menghrajani/getting-your-first-commit-in-an-open-source-project/10150780161673947 has a checklist we could work off of.

**Comment by vCloudernBeer** [comment]
Yeah,  different level and on different project will be good.  Momentum is very important.

**Comment by jfrappier** [comment]
Nice @complexsplit - I like that (curate all the content!)

**Comment by bunchc** [comment]
@jfrappier on how basic to start with? I'd say we rehash @mjbrender's getting started with git bits, along with some time spent on tools, things like editors, and other niceities, like venv and rbenv and such. For those coming from a click to install world, getting used to the new tools is often the hard part.

**Comment by jfrappier** [comment]
@bunchc sold - and sounds like @timmycarr is on OSX setup, I could probably do Windows. Timm lets chat on format and what we cover so the episodes are on par?

**Comment by vCloudernBeer** [comment]
don't forget Linux machine along with the more popular MAC and Windows.

**Comment by mjbrender** [comment]
@jfrappier also note @chriswahl could offer a helping hand on Windows. To everyone here -- Pull Requests welcome with updates to the README. I'll actually break a version off that is the 2014 project so there's no worry about reusing the master branch. (If you don't understand that sentence yet, it's okay)

**Comment by jfrappier** [comment]
EMC blocks all the things at the office; I'll get a schedule format posted to the README tonight so we can all start getting topics/agenda stuffs plugged in

**Comment by jfrappier** [comment]
I'll take that as a hint to not do the Windows setup episode @mjbrender :+1:

**Comment by vCloudernBeer** [comment]
How do we measure if we meet the goal of 30 in 30 days?  Simply 30 commits?  If we are to commit to open source project some commit may take days to complete.  In OpenStack even doc changes needs to pass unit test and code review.  Even commit message has to conform to a certain way of writing.

**Comment by jfrappier** [comment]
I don't think it will be a commit a day, but maybe it is, that's what we'll setup a tasks for. For example your 1st task might be setup a git client on your machine and create an account. Suppose at that point it's easy enough to create a repo and commit a basic readme file

**Comment by lowescott** [comment]
Great set of thoughts and ideas here! Happy to help in some way, even if it's just getting the word out.

**Comment by bunchc** [comment]
+ @Mierdin

**Comment by mjbrender** [comment]
I'm not a good hinter @jfrappier - not my intention. Just wanted you to know you have backup if you need it! It takes a village, and all that jazz.

**Comment by jfrappier** [comment]
I'm not good at online sarcasm @mjbrender :smile_cat:

**Comment by jfrappier** [comment]
@lowescott, would love some ideas on the intermediate/advanced track if you have some time

**Comment by lowescott** [comment]
@jfrappier, I'll give some thought to the intermediate tasks. I don't know if I have progressed in my own skills enough to recommend any advanced tasks!

**Comment by anthonyrhook** [comment]
Am I somewhat on the right thought plane?

Beginner tasks:
* Create an account
* Get all the tools needed on a local machine (Windows, OSX, Linux)
* Create a base repo/README.md, commit things they learn in the README.md

Would this be Advanced, or Intermediate?
* Code checkout
* Fixing a bug/committing changes to local repo
* Pull request to the maintainer
  *  Bonus points for having it pulled into main

**Comment by jfrappier** [comment]
Great start @anthonyrhook - updating the readme now for 2015. One thought I had is spend a couple weeks on Git/GitHub so folks are comfortable and move into other technologies (Ansible/PowerCLI/Rundeck) but still have everyone using GitHub for their work. Keep teaching, but also keep reinforcing the use of GitHub beyond just GitHub how-tos.

**Comment by jfrappier** [comment]
Who wants to talk branching?

**Comment by jfrappier** [comment]
@rnelson0 - **Friday 12/11** - Rebase with Rob Nelson << That work for you?

**Comment by jfrappier** [comment]
Heh: https://pbs.twimg.com/media/CSlbq0YWsAAtKiZ.png

![image](https://cloud.githubusercontent.com/assets/6105793/10854730/f0668252-7f13-11e5-8e37-006b221d4d08.png)

**Comment by rnelson0** [comment]
@jfrappier What's the format for this? If this is meant in the form of a quick lesson plan, I'm sure I can come up with a set of mucked up commits and show the path to rebasing successfully.

**Comment by jfrappier** [comment]
@rnelson0 yea - these will be shorter, more to the point - this is how you do X, so in your case rebase example/use case...boom...done

**Comment by rnelson0** [comment]
Sounds good. Any chance someone wants to take the reins on creating an
organization, so that any repos we create can be owned by the org and not
clutter up our own repos?


Rob Nelson
rnelson0@gmail.com

On Fri, Oct 30, 2015 at 4:52 PM, Jonathan Frappier <notifications@github.com

**Comment by rnelson0** [comment]
There is a vbrownbag org already with no public members, no idea if that's someone here or another group. If that's not us, I'll make another org but I don't know what name to use. @jfrappier @bunchc @mjbrender

**Comment by Mierdin** [comment]
How can I help?

**Comment by jfrappier** [comment]
@rnelson0 go ahead and set something up; we can use it throughout the series as a place for pull to work from.

@Mierdin I was thinking starting around week 3 we show people how GitHub is used in day to day life, so maybe a short episode on network config and storing in GitHub? Want to make a change to a switch port, do it, mess up, roll back etc all via GitHub?

**Comment by rnelson0** [comment]
@jfrappier: any ideas for other org names then? 'Professionalvmware'
persist a VMware centric focus I think we want to reduce right? Damn wish
there was a way to find out who has vbrownbag.

On Saturday, October 31, 2015, Jonathan Frappier <notifications@github.com>
wrote:

> @rnelson0 <https://github.com/rnelson0> go ahead and set something up; we
> can use it throughout the series as a place for pull to work from.
>
> @Mierdin <https://github.com/Mierdin> I was thinking starting around week
> 3 we show people how GitHub is used in day to day life, so maybe a short
> episode on network config and storing in GitHub? Want to make a change to a
> switch port, do it, mess up, roll back etc all via GitHub?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mjbrender/12-days-of-commitmas/issues/12#issuecomment-152733152>
> .
>


-- 

Rob Nelson
rnelson0@gmail.com

**Comment by jfrappier** [comment]
I'll ask the folks if any of them own it, anything you can plan off of vBrownBag? Commitmas? or vBrownBag and Commitmas?

**Comment by rnelson0** [comment]
Duh perfect. I was too focused on one thing :)

Will start setting that up this weekend.

On Saturday, October 31, 2015, Jonathan Frappier <notifications@github.com>
wrote:

> I'll ask the folks if any of them own it, anything you can plan off of
> vBrownBag? Commitmas? or vBrownBag and Commitmas?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mjbrender/12-days-of-commitmas/issues/12#issuecomment-152734321>
> .
>


-- 

Rob Nelson
rnelson0@gmail.com

**Comment by rnelson0** [comment]
Invites are going out now. If you'd like to be a part of the commitmas
organization, user or administrator, drop a note in here!
https://github.com/commitmas

@mjbrender: I noticed you started updating 12-days-of-commitmas. Do we want
to start a new repo, maybe we do one per year for the "main" repo and then
let members set up additional repos for their challenges?


Rob Nelson
rnelson0@gmail.com

**Comment by vCloudernBeer** [comment]
I am in.  Cannot make comments on https://github.com/commitmas

**Comment by mjbrender** [comment]
@rnelson0 good call -- I like the idea of new ones per year.

**Comment by Mierdin** [comment]
@jfrappier I typically advocate the separation of syntax and data in storing configuration artifacts in Git, so I can demo changes to that. Probably something like an Ansible playbook with a vars file, and how to make changes to that to effect network configurations. Sound helpful?

Also, should I be in the commitmas org as well? /cc @rnelson0

**Comment by rnelson0** [comment]
I threw out a few more invites. Everyone so far is an owner and if you go into settings you can make yourself visible so I'm not the bottleneck on invites :)

**Comment by bunchc** [comment]
@mjbrender it throws me for a loop that your avatars are different on the different platforms I know you on. Not a bad thing, just have to contextualise.

**Comment by jfrappier** [comment]
@Mierdin that sounds great! Any dates between Monday 12/14 and Wednesday 12/30 that dont work for your (No shows on Sat/Suns or 24th and 25th)

**Comment by Mierdin** [comment]
@jfrappier So far, the only conflict is the 19th - I'm traveling all day then. I'll let you know if anything else comes up.

**Comment by jfrappier** [comment]
I put you down for 12/21 - let me know if that doesn't work or just edit
https://github.com/commitmas/30-days-of-commitmas-2015

**Comment by Mierdin** [comment]
@jfrappier got it. Thanks!

**Comment by Mierdin** [comment]
@jfrappier I can also take on one of the presos on 12/8 or 12/9 if you're still looking for someone for those. If so, I don't have a preference between the two - up to you.

**Comment by rnelson0** [comment]
@Mierdin You've got an invite waiting for you at https://github.com/commitmas - after that you'll be able to edit the calendar as well!

**Comment by mjbrender** [comment]
I'm going to call this officially bigger. Thanks for the push @bunchc and stepping up to the challenge @rnelson0 & @jfrappier. You two are killing it. I'm going to clean up this repo as a historical reference and focus on updates to the 2015 event: https://github.com/commitmas/30-days-of-commitmas-2015
